---
title: "HW6"
author: "DZ"
date: "November 19, 2018"
output: github_document
---

```{r setup, include=FALSE,warning=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
```

## Problem 1

### tidy data
```{r,message=F}
df_homicide <- read_csv('./data/homicide_data.csv') %>%
  janitor::clean_names()%>%
  mutate(city_state = paste(city,state,sep = ',')) %>% 
  filter(city_state!='Dallas,TX'&city_state!='Phoenix,AZ'&city_state!='Kansas City,MO'&city_state!='Tulsa,AL') %>% 
  mutate(resolved = as.numeric(disposition == "Closed by arrest"),
         victim_race = as.factor(victim_race),
         victim_age = as.numeric(victim_age),
         victim_sex = as.factor(victim_sex)) %>% 
  mutate(victim_race = fct_recode(victim_race, 
                                  non_white='Asian',
                                  non_white='Black',
                                  non_white='Hispanic',
                                  non_white='Other',
                                  non_white='Unknown',
                                  white='White')) %>% 
  mutate(victim_race = fct_relevel(victim_race,'white'))
```

### Baltimore,MD
```{r}
glm.1 <- df_homicide %>% 
  filter(city_state=='Baltimore,MD') %>% 
  select(resolved, victim_age, victim_race, victim_sex) %>% 
  glm(resolved ~., data=., family = binomial()) 

glm.1.sum <- broom::tidy(glm.1) %>% 
  mutate(OR = exp(estimate)) %>%
  rename(log_OR = estimate) %>%
  select(term, log_OR , OR, p.value) 

conf_int.1 <- exp(confint(glm.1))

knitr::kable(cbind(glm.1.sum,conf_int.1)[,-1])

```

From this generalied linear model summary, we can conclude that homicides in which the victim is non-white are substantially less likely to be resolved that those in which the victim is white, the adjusted OR is 0.4406, 95%CI (0.312, 0.620).

## Calculating OR and CI for each city
```{r,warning=F,message=F}
adjusted.or <- function(x){

  glm.1 <-glm(resolved ~victim_age+ victim_race+ victim_sex, data=x, family = binomial()) 

glm.1.sum <- broom::tidy(glm.1) %>% 
  mutate(OR = exp(estimate)) %>%
  rename(log_OR = estimate) %>%
  select(term, log_OR , OR, p.value) 

conf_int.1 <- exp(confint(glm.1))

cbind(glm.1.sum,conf_int.1)[3,-c(1,2)]


}

df_all_or <- nest(df_homicide,-city_state) %>% 
  mutate(adjusted_or = map(data,adjusted.or)) %>% 
  select(city_state,adjusted_or) %>%
  unnest %>% 
  rename(low.conf = '2.5 %', high.conf = '97.5 %') 

  knitr::kable(df_all_or)

ggplot(df_all_or, aes(x=reorder(city_state, -OR),y=OR))+
    geom_histogram(stat = 'identity',alpha=.5)+
  geom_errorbar(mapping=aes(x=city_state, ymin=low.conf, ymax=high.conf), width=0.1, size=1, color="black",alpha=.5)+
    coord_flip()+
  xlab('Cities')+
  ylab('The adjusted OR with 95CI')+
  ggtitle('The adjusted OR with 95%CIs for each city')
```

